# Generated by Django 4.0.5 on 2022-07-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_categorysubscribers_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='category_thru',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorysubscribers',
            old_name='subscriber_thru',
            new_name='user',
        ),
    ]
