# Generated by Django 4.0.8 on 2022-12-04 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_authorsubscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AuthorSubscribers',
        ),
    ]
