# Generated by Django 4.0.8 on 2022-12-04 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_author_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='name_en_us',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_en',
            new_name='text_en_us',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_en',
            new_name='text_en_us',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_en',
            new_name='title_en_us',
        ),
    ]
